---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: slurm-install
    run_list:
      - recipe[slurm::install]

  - name: slurm-config
    run_list:
      - recipe[slurm::config]

  - name: slurm-nodb
    run_list:
      - recipe[slurm::slurm]

  - name: slurm-dblocal
    run_list:
      - recipe[slurm_local_mysql]
