---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: ubuntu-14.04

suites:
  - name: munge-databag-key
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[slurm::munge]
    attributes:
      slurm:
        mungekey:
          type: "databag"
  - name: munge-default
    run_list:
      - recipe[slurm::munge]

  - name: slurm-install
    run_list:
      - recipe[apt]
      - recipe[slurm::install]

  - name: slurm-config
    run_list:
      - recipe[apt]
      - recipe[slurm::config]

  - name: slurm-nodb
    run_list:
      - recipe[apt]
      - recipe[slurm::slurm]

  - name: slurm-dblocal
    attributes:
    run_list:
      - recipe[apt]
      - recipe[slurm::_test_mysql]
